// <auto-generated />
using System;
using DataAccess.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.DbContext.Migrations.PostgresDbContext
{
    [DbContext(typeof(MainDbContext.PostgresDbContext))]
    [Migration("20260519035722_miInitial")]
    partial class miInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkMessagePayloadDaM", b =>
                {
                    b.Property<Guid>("BenchmarkMessagePayloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("BenchmarkRunId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncapsulatedKey")
                        .HasColumnType("bytea");

                    b.Property<string>("FilePath")
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("MacTag")
                        .HasColumnType("bytea");

                    b.Property<int>("MessageIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PlaintextBytes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWireBytes")
                        .HasColumnType("integer");

                    b.HasKey("BenchmarkMessagePayloadId");

                    b.HasIndex("BenchmarkRunId");

                    b.ToTable("BenchmarkMessagePayload", "benchmark");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkMessageResultDaM", b =>
                {
                    b.Property<Guid>("BenchmarkMessageResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BenchmarkRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("CiphertextBytes")
                        .HasColumnType("integer");

                    b.Property<double>("DecryptMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<bool>("DecryptSuccess")
                        .HasColumnType("boolean");

                    b.Property<int>("EncapsulatedKeyBytes")
                        .HasColumnType("integer");

                    b.Property<double>("EncryptMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<int>("EncryptionOverheadBytes")
                        .HasColumnType("integer");

                    b.Property<long>("GcAllocatedBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("GcGen0Collections")
                        .HasColumnType("integer");

                    b.Property<int>("MacTagBytes")
                        .HasColumnType("integer");

                    b.Property<int>("MessageIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PlaintextBytes")
                        .HasColumnType("integer");

                    b.Property<double>("SignMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("SignalRTransitMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalRoundTripMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalWireBytes")
                        .HasColumnType("integer");

                    b.Property<double>("VerifyMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<bool>("VerifySuccess")
                        .HasColumnType("boolean");

                    b.HasKey("BenchmarkMessageResultId");

                    b.HasIndex("BenchmarkRunId");

                    b.ToTable("BenchmarkMessageResult", "benchmark");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkResourceAggregateDaM", b =>
                {
                    b.Property<Guid>("BenchmarkResourceAggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BenchmarkRunId")
                        .HasColumnType("uuid");

                    b.Property<double>("CpuAvg")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuMax")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuP50")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuP95")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuP99")
                        .HasColumnType("double precision");

                    b.Property<double>("DurationMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<int>("GcGen0Delta")
                        .HasColumnType("integer");

                    b.Property<int>("GcGen1Delta")
                        .HasColumnType("integer");

                    b.Property<int>("GcGen2Delta")
                        .HasColumnType("integer");

                    b.Property<double>("MemoryAvgMb")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryMaxMb")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryP50Mb")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryP95Mb")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryP99Mb")
                        .HasColumnType("double precision");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadPoolMaxWorkers")
                        .HasColumnType("integer");

                    b.HasKey("BenchmarkResourceAggregateId");

                    b.HasIndex("BenchmarkRunId");

                    b.ToTable("BenchmarkResourceAggregate", "benchmark");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkResourceSampleDaM", b =>
                {
                    b.Property<Guid>("BenchmarkResourceSampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BenchmarkRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("GcGen0Collections")
                        .HasColumnType("integer");

                    b.Property<int>("GcGen1Collections")
                        .HasColumnType("integer");

                    b.Property<int>("GcGen2Collections")
                        .HasColumnType("integer");

                    b.Property<double>("GcHeapMb")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryUsedMb")
                        .HasColumnType("double precision");

                    b.Property<int>("ThreadPoolWorkerThreads")
                        .HasColumnType("integer");

                    b.HasKey("BenchmarkResourceSampleId");

                    b.HasIndex("BenchmarkRunId");

                    b.ToTable("BenchmarkResourceSample", "benchmark");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkRunDaM", b =>
                {
                    b.Property<Guid>("BenchmarkRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmFamily")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AlgorithmId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("AlgorithmRunNumber")
                        .HasColumnType("integer");

                    b.Property<string>("AuthId")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Generation")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<int>("MessageSizeBytes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RunNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TlsVersion")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("WarmupCount")
                        .HasColumnType("integer");

                    b.HasKey("BenchmarkRunId");

                    b.ToTable("BenchmarkRun", "benchmark");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkSessionAggregateDaM", b =>
                {
                    b.Property<Guid>("BenchmarkSessionAggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AvgCiphertextBytes")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgDecryptMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgEncapsulatedKeyBytes")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgEncryptMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgEncryptionOverheadBytes")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgGcAllocatedBytesPerMessage")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgMacTagBytes")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgSignMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgSignalRTransitMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgTotalRoundTripMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgTotalWireBytes")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgVerifyMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BenchmarkRunId")
                        .HasColumnType("uuid");

                    b.Property<double>("MaxRoundTripMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("MinRoundTripMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("P50RoundTripMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("P95RoundTripMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("P99RoundTripMicroseconds")
                        .HasColumnType("double precision");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("double precision");

                    b.Property<int>("SuccessfulMessages")
                        .HasColumnType("integer");

                    b.Property<long>("TotalGcAllocatedBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalGcGen0Collections")
                        .HasColumnType("integer");

                    b.HasKey("BenchmarkSessionAggregateId");

                    b.HasIndex("BenchmarkRunId")
                        .IsUnique();

                    b.ToTable("BenchmarkSessionAggregate", "benchmark");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkMessagePayloadDaM", b =>
                {
                    b.HasOne("DataAccess.Models.Database.Benchmark.BenchmarkRunDaM", "Run")
                        .WithMany("Payloads")
                        .HasForeignKey("BenchmarkRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkMessageResultDaM", b =>
                {
                    b.HasOne("DataAccess.Models.Database.Benchmark.BenchmarkRunDaM", "Run")
                        .WithMany("MessageResults")
                        .HasForeignKey("BenchmarkRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkResourceAggregateDaM", b =>
                {
                    b.HasOne("DataAccess.Models.Database.Benchmark.BenchmarkRunDaM", "BenchmarkRun")
                        .WithMany()
                        .HasForeignKey("BenchmarkRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkRun");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkResourceSampleDaM", b =>
                {
                    b.HasOne("DataAccess.Models.Database.Benchmark.BenchmarkRunDaM", "BenchmarkRun")
                        .WithMany()
                        .HasForeignKey("BenchmarkRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkRun");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkSessionAggregateDaM", b =>
                {
                    b.HasOne("DataAccess.Models.Database.Benchmark.BenchmarkRunDaM", "Run")
                        .WithOne("Aggregate")
                        .HasForeignKey("DataAccess.Models.Database.Benchmark.BenchmarkSessionAggregateDaM", "BenchmarkRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("DataAccess.Models.Database.Benchmark.BenchmarkRunDaM", b =>
                {
                    b.Navigation("Aggregate");

                    b.Navigation("MessageResults");

                    b.Navigation("Payloads");
                });
#pragma warning restore 612, 618
        }
    }
}
