<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../3b.DataAccess.DbContext/DataAccess.DbContext.csproj" />
    <ProjectReference Include="../3c.DataAccess.Models/DataAccess.Models.csproj" />
    <ProjectReference Include="../4a.CrossCut.Concerns/CrossCut.Concerns.csproj" />
    <ProjectReference Include="../4b.CrossCut.Secrets/CrossCut.Secrets.csproj" />
  </ItemGroup>
</Project>
