<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>_1.Benchmark.Client</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b7e2de48-8ec1-442b-95f9-006c4458ebb7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\3c.DataAccess.Models\DataAccess.Models.csproj" />
    <ProjectReference Include="..\4b.CrossCut.Secrets\CrossCut.Secrets.csproj" />
  </ItemGroup>

</Project>